set(CMAKE_INCLUDE ${PROJECT_SOURCE_DIR}/cmake)

if(BNG_IS_WINDOWS)
	set(BNG_IS_DESKTOP TRUE)
	set(BNG_IS_MSVC TRUE)
	add_definitions(BNG_IS_WINDOWS BNG_IS_DESKTOP)
elseif(BNG_IS_LINUX)
	set(BNG_IS_DESKTOP TRUE)	
	set(BNG_IS_CLANG TRUE)
	add_definitions(BNG_IS_LINUX BNG_IS_DESKTOP)	
elseif(BNG_IS_MACOS)
	set(BNG_IS_DESKTOP TRUE)
	set(BNG_IS_APPLE TRUE)	
	set(BNG_IS_CLANG TRUE)
	add_definitions(BNG_IS_MACOS BNG_IS_APPLE BNG_IS_DESKTOP)
elseif(BNG_IS_IOS)
	set(BNG_IS_MOBILE TRUE)
	set(BNG_IS_APPLE TRUE)
	set(BNG_IS_CLANG TRUE)
	add_definitions(BNG_IS_IOS BNG_IS_APPLE BNG_IS_MOBILE)	
elseif(BNG_IS_ANDROID)
	set(BNG_IS_MOBILE TRUE)	
	set(BNG_IS_CLANG TRUE)
	add_definitions(BNG_IS_ANDROID BNG_IS_MOBILE)	
else()
	message(FATAL_ERROR "add case for ${BNG_PLATFORM}")
endif()

if(BNG_IS_CLANG)
	add_definitions(BNG_IS_CLANG)	
	add_compile_options(-Wall -Werror -fno-exceptions -fno-rtti -std=c++20)
elseif(BNG_IS_MSVC)
	add_definitions(BNG_IS_MSVC)		
	add_compile_options(/Wall /Werror /GR- /EHsc /std:c++20)
else()
	message(FATAL_ERROR "unsupported compiler.")
endif()

set(OPTIMIZED_BUILD_TYPE BNG_DEBUG CACHE STRING "what it says on the tin")
set_property(CACHE OPTIMIZED_BUILD_TYPE PROPERTY STRINGS BNG_DEBUG BNG_RELEASE)

add_definitions($<$<CONFIG:Debug>:BNG_DEBUG> $<$<CONFIG:RelWithDebInfo>:${OPTIMIZED_BUILD_TYPE}>)
